source 'https://rubygems.org'

gem 'rake', '~> 12.3'
gem 'rake_terraform', '~> 0.20'
gem 'rake_docker', '~> 0.14'
gem 'confidante', '~> 0.7'
gem 'docker-api', '~> 1.33'
gem 'semantic', '~> 1.4', '>= 1.4.1'
gem 'dotenv', '~> 2.2'
gem 'activesupport', '~> 5.1', '>= 5.1.1'
